name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: echo $DOCKER_TOKEN | docker login --username cdapdev2020 --password-stdin
      

      - name: Build Docker image
        run: docker build -t cdapdev2020/DjangoApiAuthJwt:latest .

      - name: Push Docker image
        run: docker push cdapdev2020/DjangoApiAuthJwt:latest
